environment: prod
project: pfeifer
region: westeurope

vnet:
  address_space:
    - 10.129.0.0/23
  subnets:
    - name: subnet-1
      address_prefixes: ["10.129.0.0/24"]
    - name: subnet-2
      address_prefixes: ["10.129.1.0/24"]
