---
name: Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.9.8

jobs:
  check:
    runs-on: ubuntu-22.04
    environment:
      name: ${{ inputs.environment }}
    name: Terraform Format Check
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check

  dev:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && inputs.environment == 'dev'
    environment:
      name: dev
    name: Terraform Plan and Apply
    needs: check
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace
        run: terraform workspace select ${{ inputs.environment }}

      - name: Terraform Plan
        run: terraform apply

  prod:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && inputs.environment == 'prod'
    needs: dev
    environment:
      name: prod
    name: Terraform Plan and Apply
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace
        run: terraform workspace select ${{ inputs.environment }}

      - name: Terraform Plan
        run: terraform apply
